[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "ml-switcheroo-ir"
version = "0.1.0"
description = "Intermediate Representation for ml-switcheroo"
authors = [
    { name = "ml-switcheroo authors" }
]
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["dependencies", "optional-dependencies"]

[project.scripts]
ml-switcheroo-ir = "ml_switcheroo_ir.cli:main"

[project.urls]
Homepage = "https://github.com/ml-switcheroo/ml-switcheroo-ir"

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
test = ["requirements-test.txt"]
cuda = ["requirements-cuda.txt"]

[tool.ruff]
exclude = [
    "third_party",
]

[tool.hatch.metadata]
allow-direct-references = true
