[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "ml-switcheroo-ir"
version = "0.0.3"
description = "Intermediate Representation for ml-switcheroo* and ml-framework-snapshots"
authors = [
    { name = "Samuel Marks <807580+SamuelMarks@users.noreply.github.com>" }
]
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["dependencies", "optional-dependencies"]

[project.scripts]
ml-switcheroo-ir = "ml_switcheroo_ir.cli:main"

[project.urls]
Homepage = "https://github.com/ml-switcheroo/ml-switcheroo-ir"

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
test = ["requirements-test.txt"]

[tool.ruff]
exclude = ["third_party"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.coverage.run]
branch = true

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "tabulate.*"
ignore_missing_imports = true

